Change: (verify) Mount repo instead of restoring files
Instead of restoring files to a temporary directory and then deleting
them, mount the repo and compare them that way.  Safer, simpler, and
maybe faster.

diff --git a/restic-runner b/restic-runner
--- a/restic-runner
+++ b/restic-runner
@@ -71,7 +71,7 @@ function log {
 }
 
 function cleanup {
-    # Remove temporary paths (${temp_files[@]}).
+    # Remove temporary paths (${temp_paths[@]}).
     for path in "${temp_paths[@]}"
     do
         if [[ -r $path ]]
@@ -82,6 +82,13 @@ function cleanup {
             debug "Temporary path doesn't exist, not deleting: $path"
         fi
     done
+
+    if [[ $mount_point ]]
+    then
+        debug "Unmounting repo from: $mount_point"
+
+        fusermount -u "$mount_point" || error "Unable to unmount repo from: $mount_point"
+    fi
 }
 
 function verbose {
@@ -370,95 +377,93 @@ function verify-randomly {
     # ($snapshot, default to latest) by restoring them to a temporary
     # directory and checking Restic's exit status.
 
-    # MAYBE: It might be faster (or at least, use less disk space and be
-    # slightly safer) to FUSE-mount the repo and compare against it rather
-    # than restoring to a temp dir.
+    debug "Verifying randomly..."
 
     # Disable disk usage report for this command since the repo size
     # doesn't change from it.
     unset du
 
+    # Number of files.  In order to get paths to files and not
+    # directories, we must check the type of each path.  Since some
+    # paths might be directories, and if discarded would decrease the
+    # number of files checked, we use a much greater number and then
+    # gather the actual number of files that we want.
     local num_files=${rest:-10}
+    local num_paths=$((num_files * 100))
 
     # Get snapshot ID.
     local snapshot=$snapshot
     if ! [[ $snapshot ]] ||  [[ $snapshot = latest ]]
     then
+        debug "Getting latest snapshot ID..."
         snapshot=$(snapshot-ids | tail -n1) || die "Unable to get latest snapshot ID"
     fi
 
-    # Make temp dir.
-    local temp_restore_dir=$(mktemp -d) || die "Unable to make temp dir"
-    temp_paths+=("$temp_restore_dir")
+    # Get paths from snapshot.
+    debug "Listing $num_paths paths in snapshot: $snapshot"
+    local paths
+    readarray -t paths < <(restic ls $snapshot | shuf -n $num_paths)
+    [[ $paths ]] || die "Unable to list paths in snapshot: $snapshot"
 
-    # Remove restored files when finished or aborted.
-    # NOTE: If any restored files are read-only, they will fail to be
-    # removed.  Not a big deal, since they're in a temp directory.
+    # Mount repo.  Since "restic mount" doesn't background itself (even
+    # though it says to unmount when done, while simply SIGINT'ing it
+    # causes it to unmount and exit), we have to background it, save its
+    # PID, and then spin, waiting for the mounted repo to become available.
+    local mount_output=$(mktemp) || die "Unable to make temp output file."
+    temp_paths+=("$mount_output")
     trap cleanup EXIT INT TERM
 
-    # Get paths from snapshot.
-    local paths
-    readarray -t paths < <(restic ls $snapshot | shuf -n $num_files)
-    [[ $paths ]] || die "Unable to list paths in snapshot: $snapshot"
+    mount_point=$(mktemp -d) || die "Unable to make temp mount point dir."
+
+    debug "Mounting repo at: $mount_point"
+    mount "$mount_point" &>"$mount_output" &
+
+    local attempts=0
+    while [[ 1 ]]
+    do
+        if [[ $attempts -ge 10 ]]
+        then
+            die "Mounted repo never became available."
+            break  # Not sure if necessary, but it might be sometimes.
+        fi
+
+        if grep "Now serving the repository" "$mount_output"
+        then
+            debug "Mounted repo available: proceeding..."
+            break
+        else
+            ((attempts++))
+            debug "Mounted repo not yet available ($attempts attempts): waiting..."
+            sleep 1
+        fi
+    done
 
     log "VERIFYING $num_files files from snapshot $snapshot..."
 
-    # Build the command and then eval it.  This is necessary to
-    # process the "--include" options, which may include paths with
-    # spaces, which must be quoted, so the whole command must be
-    # eval'ed by Bash to separate the arguments.
+    local snapshot_prefix="$mount_point/ids/$snapshot/"
 
-    # TODO: If Restic had an --include-from option that accepted a
-    # filename, it would make this easier.
-    local command="restic \
-          restore -t $temp_restore_dir \
-          $(echo_option_with_arg include paths) \
-          $snapshot"
-    eval "$command" || die "Verify failed"
+    # Compare with live versions
+    log "COMPARING with live versions..."
 
-    if [[ $compare ]]
-    then
-        # Compare with live versions
-        log "COMPARING with live versions..."
-        for path in "${paths[@]}"
-        do
-            if [[ -d $path ]]
-            then
-                compare_dir "$path"
-            elif [[ -f $path ]]
-            then
-                compare_file "$path"
-            fi
-        done
-    fi
-}
-
-function compare_file {
-    # Compare file at path ($1) to version at $temp_restore_dir/$1.
-    local restored_file="${temp_restore_dir}${1}"
-    local live_file="$1"
-
-    verbose "Comparing file: $live_file"
-    cmp "$live_file" "$restored_file" || error "File differs: $live_file"
-}
-
-function compare_dir {
-    # Compare files in directory at path ($1) to versions at $temp_restore_dir/$1.
-    local path="$1"
-    local restored_dir="${temp_restore_dir}${path}"
-
-    # Find files in restored directory.
-    local restored_files
-    readarray -t restored_files < <(find "$restored_dir" -type f)
-    [[ $restored_files ]] || die "Unable to list files in restored directory: $restored_dir"
-
-    # Compare restored files with live versions.
-    for restored_file in "${restored_files[@]}"
+    local num_compared=0
+    for path in "${paths[@]}"
     do
-        local live_file=${restored_file#$temp_restore_dir}  # Remove temp dir from path
+        [[ $num_compared -ge $num_files ]] && break
 
-        verbose "Comparing file: $live_file"
-        cmp "$live_file" "$restored_file" || error "File differs: $live_file"
+        local snapshotted_path="${snapshot_prefix}/${path}"
+
+        if [[ -d $path ]]
+        then
+            debug "Ignoring directory: $snapshotted_path"
+
+        elif [[ -f $path ]]
+        then
+            debug $(printf "Comparing file %q to %q" "$path" "$snapshotted_path")
+            verbose $(printf "Comparing file: %q" "$path")
+
+            cmp "$path" "$snapshotted_path" || error "File differs: $path"
+            ((num_compared++))
+        fi
     done
 }
 
